project:
  type: website

execute:
  freeze: auto

website:
  title: "O2iginal's Blog"
  site-url: "https://zipzipgo.xyz"
  navbar:
    right:
    - about.qmd
    - icon: github
      href: https://github.com/O2iginal
    # - icon: twitter
    #   href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css
